### ISSUE TITLE
Documenter tous les modules VEAF

### ISSUE THREAD

**Issue by davidp57** [VEAF/documentation#6]
```[tasklist]
### Tasks
- [x] AirWaves
- [ ] QRA
- [ ] Assets
- [ ] Opérations aéronavales
- [ ] Interpréteur
- [ ] Combat missions (air-air)
- [ ] Combat zones (air-sol)
- [ ] FARPs et pistes en herbe
- [ ] CTLD
- [ ] Hound Elint
- [ ] Points d'intérêt
- [ ] Menus radio
- [ ] Accès à distance
- [ ] Zone sanctuaire
- [ ] Gestion des accès et de la sécurité
- [ ] Skynet IADS
- [ ] Move (déplacement de groupes d'aéronefs: tankers, afac, etc.)
- [ ] Génération d'une mission de transport (hélico)
```
