### ISSUE TITLE
Documenter tous les outils VEAF

### ISSUE THREAD

**Issue by davidp57** [VEAF/documentation#7]
```[tasklist]
### Tasks
- [ ] Injecteur de groupes d'aéronefs
- [ ] Injecteur de plans de vols
- [ ] Injecteur de presets radio
- [ ] Génération de versions (date / heure / météo)
```
